### ISSUE TITLE
[⚡] New v9.0.0 release with massive changes

### ISSUE THREAD

**Issue by bkimminich** [OWASP/pwning-juice-shop_ES#2]
Today the v9.0.0 version of the ebook was released. It contains _massive_ changes and extended content. If you want to continue with this translation effort (which to me seems very much stalled at the moment...) please rebase with `master` of https://github.com/bkimminich/pwning-juice-shop.

If you do not plan to catch up and continue with the translation, please let me know and I will close this repository for future commits and ask it to be removed. As initially stated, I do not want Juice Shop users to be confused by unfinished spin-offs of the official documentation.

**Comment by CarlosAllendes** [comment]
Hi Bjorn

Thanks for the information, we will be happy to work in this new version.
In fact, 2 new colleagues will be added in September with the exclusive
purpose of finishing this translation before October.

Thank you for your kindness (and patience).

----------
Carlos Allendes Droguett
*UK. STEM Ambassador "desde 2019"*
*OWASP Chile President"desde 2010"*
www.owaspCHILE.org <http://www.owaspchile.org/>
----------
www.linkedin.com/in/carlosallendes
GO OWASP !     www.OwaspLatamTour.org <http://www.owasplatamtour.org/>
----------

**Comment by bkimminich** [comment]
I just copied over all new content from my original version and manually copied back your previous translations in `solutions.md` where the challenges have not changed. So, you should be good to continue - but the still open PR #1 will probably need some rework before being merged now.

Also, one important note: You are translating the challenge headlines, which are identical with the description in the application itself today. This causes some issues with links within the book right now. Also, in the Juice Shop application the challenge names and descriptions are _currently_ not translatable, so someone might have a harder time finding the right solution if they cannot search for the English text in the translated book.

The best solution would be to make the challenges translatable at some point, but this would not be so easy right now due to the format they are saved in and the way they are processed.

**Comment by bkimminich** [comment]
Okay, I took care of the PR #1 and merged it.
